var soap = require('soap');
var url = 'https://sandbox.gestpay.net/gestpay/gestpayws/WSs2s.asmx?WSDL';

soap.createClientAsync(url)
    .then((client) => {
        return client.callPagamS2SAsync({
            shopLogin: 'GESPAY65987',
            uicCode: '242',
            amount: '13.07',
            shopTransactionId: 'abcdef',
            tokenValue: '47L76F84UBQK2026' // please insert a valid token for your shopCode, generated by Gestpay
        });
    }).then((result) => {
        console.log(result);
    });